spring.application.name=bookie
spring.datasource.url=jdbc:postgresql://localhost:5432/bookie
spring.datasource.username=bookie
spring.datasource.password=bookie_dev_password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=50